<div class="py-4 w-100 text-center" id=<?=$loading_id?>>
    <div class="ant-empty-image">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
            style="margin: auto; background: none; display: block; shape-rendering: auto;" width="100px" height="100px"
            viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
            <path d="M18 50A32 32 0 0 0 82 50A32 36 0 0 1 18 50" fill="#007bff" stroke="none">
                <animateTransform attributeName="transform" type="rotate" dur="0.33898305084745767s"
                    repeatCount="indefinite" keyTimes="0;1" values="0 50 52;360 50 52" />
            </path>
            <!-- [ldio] generated by https://loading.io/ -->
        </svg>

    </div>
</div>